### ISSUE TITLE
ArduinoIDE showing wrong free-space

### ISSUE THREAD

**Issue by Pascal2511** [thelastoutpostworkshop/ESP32PartitionBuilder#1]
Hello, first of all i realy like the partition-builder! But I camoe over a problem:
I created the partition as shown as on the picture, and it works fine. But when uploading the free-space is always shown wrong in the ArduinoIDE.
![image](https://github.com/user-attachments/assets/c4838e9a-bd9a-4d76-8329-63c3b491c99f)

![image](https://github.com/user-attachments/assets/2936b2f8-d807-4631-a8fc-8bc6331b087c)

**Comment by thelastoutpostworkshop** [comment]
When using custom partitions, by default Espressif sets the maximum upload size at 16MB.
If you want to set it based on your dev board actual size, for example 4MB, you have to edit manually the boards.txt file installed with Espressif Core.
It is normally located in Users\[your user name]\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.4 
In that file you have to locate your dev board (it's not easy...) and change the size of custom.upload.maximum corresponding to your dev board size.
This file will be overwritten when you update or reinstall Espressif Core.
